basis/urls.py
from django.urls import path, reverse_lazy
from . import views
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views


class MyHackedView(auth_views.PasswordResetView):
    success_url = reverse_lazy('basis:password_reset_done')


app_name = 'basis'
urlpatterns = [
    path('', views.index_page, name='index_page'),
    path('run_services/', views.run_services, name="run_services"),
    path('contacts/', views.contacts, name='contacts'),
    path('about/', views.about, name='about'),
    path('all_education/', views.all_education, name='all_education'),
    path('<slug:slug>/<int:graduated>', views.detailed_education, name='detailed_education'),
    path('all_experience/', views.all_experience, name='all_experience'),
    path('<slug:slug>/<str:company_name>/<str:position>', views.detailed_experience,
         name='detailed_experience'),

    path('contact_form/', views.contact_form, name="contact_form"),
    path('messages/', views.all_messages, name='all_messages'),

    path('upload_documents/', views.document_form_upload, name='upload_documents'),

    path('all_portfolio/', views.all_portfolio, name='all_portfolio'),
    path('<slug:slug>/<str:project_name>', views.detailed_portfolio, name='detailed_portfolio'),

    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),

    path('password_reset/', MyHackedView.as_view(), name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(
        success_url=reverse_lazy('basis:password_reset_complete'),
    ), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),

    path('profile/', views.profile, name='profile'),
    path('edit_profile/', views.edit_profile, name='edit_profile'),

    path('register/', views.register, name='register'),

    path('news/', views.all_news, name='all_news'),
    path('subscribe/', views.mailing_news, name='subscribe')

]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

smatova_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('basis/', include('basis.urls', namespace='basis')),
    path('social-auth/', include('social_django.urls', namespace="social")),

]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

basis/models.py
from django.conf import settings
from django.db import models
from django.urls import reverse
from django.utils import timezone
from django.contrib.auth.models import User


class Education(models.Model):
    graduated = models.PositiveSmallIntegerField()
    school_name = models.CharField(max_length=255)
    course_name = models.CharField(max_length=255)
    description = models.TextField(blank=True)
    certificate = models.ImageField(blank=True)
    slug = models.SlugField(max_length=255, unique='course_name')

    def __str__(self):
        return self.course_name

    def get_absolute_url(self):
        return reverse('basis:detailed_education',
                       args=[self.slug,
                             self.graduated,
                             ])


class Experience(models.Model):
    start_date = models.PositiveSmallIntegerField()
    end_date = models.PositiveSmallIntegerField(null=True, blank=True)
    company_name = models.CharField(max_length=255)
    position = models.CharField(max_length=255)
    description = models.TextField(blank=True)
    industry = models.CharField(max_length=255, blank=True)
    slug = models.SlugField(max_length=255, unique='company_name')

    def __str__(self):
        return self.position

    def get_absolute_url(self):
        return reverse('basis:detailed_experience',
                       args=[self.slug,
                             self.company_name,
                             self.position
                             ])


class Portfolio(models.Model):
    project_name = models.CharField(max_length=255)
    description = models.TextField(blank=True)
    link = models.URLField(blank=True)
    slug = models.SlugField(max_length=255, unique='project_name')
    date = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.project_name

    def get_absolute_url(self):
        return reverse('basis:detailed_portfolio',
                       args=[self.slug,
                             self.project_name])


class Messages(models.Model):
    name = models.CharField(max_length=100)
    sender_email = models.EmailField()
    message = models.CharField(max_length=1000)
    subject = models.CharField(max_length=255)
    date = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.sender_email


class UploadDocument(models.Model):
    description = models.CharField(max_length=255, blank=True)
    document = models.FileField(upload_to='documents/')
    file_name = models.CharField(max_length=255)
    date = models.DateTimeField(auto_now_add=True)


class Profile(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL,
                                on_delete=models.CASCADE)
    hr = models.BooleanField(default=False)
    subscribed_for_mailings = models.BooleanField(default=False, blank=True)
    subscription_email = models.EmailField(default="", blank=True)

    def __str__(self):
        return str(self.user)


class TopNews(models.Model):
    title = models.CharField(max_length=300)
    body = models.TextField()
    link = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    slug = models.SlugField(max_length=300, unique='title', default='')

basis/forms.py
from django import forms
from django.contrib.auth.models import User

from . import models


class ContactForm(forms.ModelForm):
    class Meta:
        model = models.Messages
        fields = ('subject', 'name', 'sender_email', 'message')


class DocumentForm(forms.ModelForm):
    class Meta:
        model = models.UploadDocument
        fields = ('description', 'document')


class LoginForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)


class UserRegistrationForm(forms.ModelForm):
    password = forms.CharField(label='Pass', widget=forms.PasswordInput)
    password2 = forms.CharField(label='Pass2', widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ('username', 'email')

    def clean_password2(self):
        cd = self.cleaned_data
        if cd['password'] != cd['password2']:
            raise forms.ValidationError('bad password')
        return cd['password']


class UserEditForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('email', 'username')


class ProfileEditForm(forms.ModelForm):
    class Meta:
        model = models.Profile
        fields = ('subscribed_for_mailings', 'subscription_email', )


class MailingForm(forms.ModelForm):
    class Meta:
        model = models.Profile
        fields = ('subscribed_for_mailings', 'subscription_email', )

basis/views.py
from basis import forms
from basis import models
from datetime import date
from django.contrib.auth import authenticate
from django.contrib.auth import login
from django.contrib.auth.decorators import login_required
from django.core.mail import send_mail
from django.http import HttpResponse
from django.shortcuts import get_object_or_404
from django.shortcuts import render
from .tasks import run_background

SUBJECT = ' {name} sent you a message.'
BODY = '{message}'


def all_education(request):
    educations = models.Education.objects.order_by('-graduated')
    return render(request, "education/all_education.html",
                  {'educations': educations})


def detailed_education(request, slug, graduated):
    education = get_object_or_404(models.Education,
                                  slug=slug,
                                  graduated=graduated)
    return render(request, "education/detailed_education.html",
                  {'education': education})


def all_experience(request):
    experiences = models.Experience.objects.order_by('-start_date')
    return render(request, "experience/all_experience.html",
                  {'experiences': experiences})


def detailed_experience(request, slug, company_name, position):
    experience = get_object_or_404(models.Experience,
                                   slug=slug,
                                   company_name=company_name,
                                   position=position)
    return render(request, "experience/detailed_experience.html",
                  {'experience': experience})


def index_page(request):
    if request.user.is_superuser:
        return render(request, 'index_master.html')
    return render(request, 'index.html')


def contacts(request):
    return render(request, 'contacts.html')


def about(request):
    return render(request, 'about.html')


def all_portfolio(request):
    portfolios = models.Portfolio.objects.all()
    return render(request, "portfolio/all_portfolio.html",
                  {'portfolios': portfolios})


@login_required  # ограничиваем доступ
def detailed_portfolio(request, slug, project_name):
    portfolio = get_object_or_404(models.Portfolio,
                                  slug=slug,
                                  project_name=project_name)
    return render(request, "portfolio/detailed_portfolio.html",
                  {'portfolio': portfolio})


def contact_form(request):
    sent = False

    if request.method == 'POST':
        form = forms.ContactForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            subject = SUBJECT.format(name=cd['name'])
            body = BODY.format(message=cd['message'])
            success = send_mail(subject, body, 'my@mail.com', ['tatsm.reg@gmail.com'])
            if success:
                new_message = form.save(commit=False)
                new_message.name = new_message.name
                new_message.sender_email = new_message.sender_email
                new_message.subject = new_message.subject
                new_message.message = new_message.message
                new_message.save()
                sent = True
    else:
        form = forms.ContactForm()
    return render(request,
                  "contact_form.html",
                  {'form': form, 'sent': sent})


def document_form_upload(request):
    upload = False
    if request.method == 'POST':
        form = forms.DocumentForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            upload = True
    else:
        form = forms.DocumentForm()
    return render(request,
                  'upload_documents.html',
                  {'form': form, 'upload': upload})


def custom_login(request):
    if request.method == "POST":
        form = forms.LoginForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            user = authenticate(
                username=cd['username'],
                password=cd['password'],
            )
            if user is not None:
                if user.is_active:
                    login(request, user)
                    return HttpResponse('logged in')
                else:
                    return HttpResponse('User not active')
            else:
                return HttpResponse('Bad credentials')

    else:
        form = forms.LoginForm()
    return render(request,
                  'login.html',
                  {'form': form})


def profile(request):
    return render(request, "profile.html", {'user': request.user})


def register(request):
    if request.method == "POST":
        form = forms.UserRegistrationForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            new_user = form.save(commit=False)
            new_user.set_password(cd['password'])
            new_user.save()
            models.Profile.objects.create(user=new_user)

            return render(request, "registration_complete.html",
                          {"user": new_user})

    else:
        form = forms.UserRegistrationForm()
        return render(request, "register.html", {'form': form})


def edit_profile(request):
    if request.method == "POST":
        user_form = forms.UserEditForm(request.POST, instance=request.user)
        profile_form = forms.ProfileEditForm(request.POST,
                                             instance=request.user.profile,
                                             )
        if all((user_form.is_valid(), profile_form.is_valid())):
            user_form.save()
            profile_form.save()
            return render(request, "profile.html", {'user': request.user})
    else:
        user_form = forms.UserEditForm(instance=request.user)
        profile_form = forms.ProfileEditForm(request.POST, instance=request.user.profile)

    return render(request, "edit_profile.html", {'user_form': user_form,
                                                 'profile_form': profile_form})


def all_news(request):
    today = date.today()
    today_news = models.TopNews.objects.filter(created__gte=today)
    return render(request, "news.html",
                  {'today_news': today_news})


@login_required
def mailing_news(request):
    if request.method == "POST":
        mailing_form = forms.MailingForm(request.POST,
                                         instance=request.user.profile,
                                         )
        if mailing_form.is_valid():
            mailing_news = mailing_form.save(commit=False)
            mailing_news.subscribed_for_mailings = mailing_news.subscribed_for_mailings
            mailing_news.subscription_email = mailing_news.subscription_email
            mailing_news.save()

            return render(request, "subscribe_complete.html",
                          {"mailing_news": mailing_news})
    else:
        mailing_form = forms.MailingForm()
    return render(request, 'subscribe.html', {"mailing_form": mailing_form})


def all_messages(request):
    messages = models.Messages.objects.all()
    return render(request, "messages.html",
                  {'messages': messages})


def run_services(request):
    run_background.delay()
    return render(request, "base.html")

basis/templates/about.html
{% extends 'base.html' %}
{% block title %}
    About
{% endblock %}
{% block body %}

    <p><h3>Hello! Nice to meet you!</h3>
    <br><br> I'm Smatova Tatiana and this is may personal page.
     <br><br>Here you can find information about me: education, experience and my portfolio.
    <br>If you want, you can download my CV or send me a message.
    <br>Also you can find some interesting news and subscribe to their newsletter if you wish.
    <br><br>Have a nice day!
    </p>
{% endblock %}

basis/templates/base.html
{% load bootstrap4 %}
{% load static %}
{% bootstrap_css %}
{% bootstrap_javascript %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %} MY DEFAULT TITLE {% endblock %}</title>
    <link href="{% static "style.css" %}" rel="stylesheet" type="text/css">
</head>
<body>
<header>
<div>

</div>
</header>

<div class="container-flex m-4">
    <div class="row">
        <div class="col-sm-2 px-sm-4 pr-sm-1">
            {% block menu %}
                <p><a href="{% url 'basis:index_page' %}">Main page</a></p>
                 {% if request.user.is_authenticated %}
                    <a href="{% url 'basis:logout' %}">logout </a><br>
                    <a href="{% url 'basis:profile' %}">profile </a>
                {% else %}
                    <a href="{% url 'basis:login' %}">login </a><br>
                    <a href="{% url 'basis:register' %}">register </a><br>
                {% endif %}
                <p><a href="{% url 'basis:index_page' %}">Main page</a></p>
                <p><a href="{% url 'basis:about' %}">About me</a></p>
            {% endblock %}
        </div>
        <div class="col-sm-10" >
            {% block body %}{% endblock %}

        </div>
    </div>
    {# footer #}
    <div class="row">
        <div class="col-sm-2 mt-2" >
            <small><i>Python web development</i></small>
        </div>
        <div class="col-sm-10 mt-2">
            <small><i>Smatova Tatiana</i></small>

        </div>
    </div>

</div>


</body>
</html>

basis/templates/contacts.html
{% extends 'base.html' %}
{% block title %}
    Contacts
{% endblock %}

{% block body %}
    <p><b>my e-mail:</b> smatova.tatiana@gmail.com</p>
    <p>You can send me a message<a href="{% url 'basis:contact_form' %}"> here</a></p>
    <p><b>LinkedIn: </b><a href="https://www.linkedin.com/in/smatovatatiana/">smatovatatiana</a></p>

{% endblock %}

basis/templates/edit_profile.html
{% extends 'base.html' %}

{% block title %}
    Edit profile
{% endblock %}

{% block body %}
        <h3>You can edit your data:</h3>
        <form action="." method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ user_form.as_p }}
                {% if user.profile.subscribed_for_mailings is True %}
                    <input type="checkbox" name="subscribed_for_mailings" id="id_subscribed_for_mailings" checked="">
                    If you don't want to receive emails anymore, uncheck
                    <br>
                    Subscription email: <input type="email" name="subscription_email" value={{ user.profile.subscription_email }} class="vTextField" maxlength="254" id="id_subscription_email">
                {% else %}
                    <label>
                        <input type="checkbox" name="subscribed_for_mailings" id="id_subscribed_for_mailings">
                        I want to subscribe for mailing news
                    </label>
                    <p><label>
                        Send news on my email:
                        <input type="email" name="subscription_email" class="vTextField" maxlength="254" id="id_subscription_email">
                    </label></p>

                {% endif %}
            <p><input type="submit" value="Update"></p>
        </form>



{% endblock %}

basis/templates/index.html
{% extends 'base.html' %}
{% block title %}
    Index Page
{% endblock %}
{% block body %}

    <p><a href="{% url 'basis:all_education' %}"> Education </a></p>
    <p><a href="{% url 'basis:all_experience' %}">Experience</a></p>
    <p><a href="{% url 'basis:all_portfolio' %}">Portfolio</a></p>
    <p><a href="{% url 'basis:contacts' %}">Contacts</a></p>
    <p><a href="{% url 'basis:all_news' %}">News</a></p>
    <p><a href="/media/documents/Smatova_Tatiana_CV_25-10-2021.pdf" download>Download my CV</a></p>
{% endblock %}

basis/templates/index_master.html
{% extends 'base.html' %}
{% block title %}
    Index Page
{% endblock %}
{% block body %}

    <p><a href="{% url 'basis:all_education' %}"> Education </a></p>
    <p><a href="{% url 'basis:all_experience' %}">Experience</a></p>
    <p><a href="{% url 'basis:all_portfolio' %}">Portfolio</a></p>
    <p><a href="{% url 'basis:contacts' %}">Contacts</a></p>
    <p><a href="{% url 'basis:all_messages' %}">Messages</a></p>
    <p><a href="{% url 'basis:all_news' %}">News</a></p>
    <p><a href="/media/documents/Smatova_Tatiana_CV_25-10-2021.pdf" download>Download my CV</a></p>
    <p><a href="{% url 'basis:upload_documents' %}">Upload document</a></p>
{% endblock %}

basis/templates/login.html
{% extends 'base.html' %}

{% block title %}
    Login page
{% endblock %}

{% block body %}
        <h1>User login:</h1>
        <form action="." method="post">
            <!--точка в форме перебрасывает в тот же url, на котором она стоит (в тот же location).
            Но location считается по / Если / нет, то он килает на его родительский-->
            {{ form.as_p }}
            {% csrf_token %}
            <input type="submit" value="Login">
        </form>
{% endblock %}

basis/templates/messages.html
{% extends 'base.html' %}

{% block title %}
    Messages for me
{% endblock %}
{% block body %}
    {% for text in messages%}
        <h3>{{ text.name }}</h3>
        <p>
        {{ text.sender_email }}, {{ text.date }}
        <br>
         {{ text.message }}
        </p>

        <hr>
    {% endfor %}

{% endblock %}

basis/templates/news.html
{% extends 'base.html' %}

{% block title %}
    News
{% endblock %}
{% block body %}
    <h1>Last news</h1> {{ news.created }}
    {% for news in today_news%}
        <h3>{{ news.title }}</h3>
        <a href="{{ news.link }}">Read this news</a>
        <hr>
    {% endfor %}

<a href="{% url 'basis:subscribe' %}">I want to receive news by mail</a>

{% endblock %}

basis/templates/portfolio.html
{% extends 'base.html' %}

{% block title %}
    My portfolio
{% endblock %}

{% block body %}
    {% for portfolio in portfolios %}
        <h2>{{ portfolio.project_name }}</h2>
        <p>
        {{ portfolio.description }}
        </p>
        <a href="{{ portfolio.link }}">See it on Github</a>
        <hr>
    {% endfor %}
{% endblock %}

basis/templates/register.html
{% extends 'base.html' %}

{% block title %}
Register user
{% endblock %}

{% block body %}
        <h3>For registration, please, fill the fields:</h3>
    <br>
        <form action="" method="post">
            {{ form.as_p }}
            {% csrf_token %}
            <input type="submit" value="Register!">
        </form>
{% endblock %}

basis/templates/registration_complete.html
{% extends 'base.html' %}

{% block title %}
    Registration complete
{% endblock %}

{% block body %}
    <h1>Hi {{ user.username }}</h1>

    You've been registered. Now you can
    <a href="{% url "basis:login" %}">login </a><br>

{% endblock %}

basis/templates/subscribe_complete.html
{% extends 'base.html' %}

{% block title %}
    Subscribing complete
{% endblock %}

{% block body %}
    <h1>Hi {{ user.username }}</h1>

    Thanks for subscribing.
    You will receive daily news by email: {{ user.profile.subscription_email }}

{% endblock %}

basis/templates/upload_documents.html
{% extends 'base.html' %}

{% block body %}
    {% if not upload %}  <!--добавляем флаг (добавлено во вьюшку) если не было отправлено, открываем форму-->
        <h1>Upload your file</h1>
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Upload</button>
        </form>
    {% else %}  <!--если отправлено-->
    <br><br> Your file has been upload

    {% endif %}

{% endblock %}